language: python
python:
  - "2.7"
  - "pypy"

# command to install dependencies
install: "pip install -r requirements.generic --use-mirrors"
install: "pip install -r requirements.py_27 --use-mirrors"
# command to run tests
script: nosetests -v
